version: "2"

services:
    frontend:
        image: surajd/frontend:devopsdays2016
        ports:
            - 8080:8080
        labels:
            kompose.service.type: LoadBalancer

    backend:
        image: tomaskral/kompose-demo-backend:kubecon2016
        ports:
            - 3000:3000
        environment:
            MONGODB_PASSWORD: pass
            MONGODB_USER: user
            MONGODB_DATABASE: db
            MONGODB_SERVER: mongodb:27017

    mongodb:
        image: tomaskral/mongodb-centos7
        ports:
            - 27017:27017
        volumes:
            - /var/lib/mongodb/data
        environment:
            MONGODB_PASSWORD: pass
            MONGODB_USER: user
            MONGODB_DATABASE: db
            MONGODB_ADMIN_PASSWORD: root

